M48
; DRILL file {KiCad 8.0.4} date 2024-09-07T18:47:57+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-07T18:47:57+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.1463Y0.4488
X1.1463Y0.2212
T2
X0.0Y1.5354
X0.0Y0.0
X1.2598Y1.5354
X1.2598Y0.0
M30
